# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c971d2ecbd3fb5bf5608219ba095087a7a8dcf3d3cccf0f413040c5e8a8dea9be182b67198bf4314f76cabe9017df1783f093c1734fdabd32369f7ec98ae9bf1

test:
  secret_key_base: cf790f141a29a21ab90f9742204d30883e93a0d688b188027265b2c68e3960ebc303d1c034928059e22310cbdf7197d3faeb2c8b4b4905a8fed9481613093d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
